-- CNS_FACTURE definition

CREATE TABLE "CNS_FACTURE" 
   (	
	"ID" NUMBER NOT NULL ENABLE, 
	"TSTAMP" DATE, 
	"AMOUNT" NUMBER, 
	"DOCTORID" VARCHAR2(50), 
	"FACTURENUMBER" VARCHAR2(50), 
	"REQUESTEDON" DATE, 
	"CNS_REFERENCE" NUMBER, 
	"DOWNLOAD_LINK" VARCHAR2(500), 
	 CONSTRAINT "CNS_FACTURE_PK" PRIMARY KEY ("ID")
   );

CREATE OR REPLACE TRIGGER "BI_CNS_FACTURE" 
  before insert on "CNS_FACTURE"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "CNS_FACTURE_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER "BI_CNS_FACTURE" ENABLE;

CREATE UNIQUE INDEX "CNS_FACTURE_PK" ON "CNS_FACTURE" ("ID") ;

GRANT SELECT ON "CNS_FACTURE" TO "COLLECTOR";


-- CNS_FACTURE foreign keys

ALTER TABLE "CNS_FACTURE" ADD CONSTRAINT "CNS_FACTURE_PAYMENT_FK" FOREIGN KEY ("CNS_REFERENCE")
	  REFERENCES "CNS_PAYMENT" ("ID") ENABLE;

-- CNS_PAYMENT definition

CREATE TABLE "CNS_PAYMENT" 
   (	
	"ID" NUMBER NOT NULL ENABLE, 
	"REFERENCE" VARCHAR2(50), 
	"AMOUNT" NUMBER, 
	"TSTAMP" DATE, 
	"DOWNLOAD_LINK" VARCHAR2(500), 
	 CONSTRAINT "CNS_PAYMENT_PK" PRIMARY KEY ("ID")
   ) ;

CREATE OR REPLACE TRIGGER "BI_CNS_PAYMENT"
	before insert on "CNS_PAYMENT"
	for each row
	begin
		if :NEW."ID" is null then
			select "CNS_PAYMENT_SEQ".nextval into :NEW."ID" from sys.dual;   
		end if; 
	end; 
/
ALTER TRIGGER "BI_CNS_PAYMENT" ENABLE;

CREATE UNIQUE INDEX "CNS_PAYMENT_PK" ON "CNS_PAYMENT" ("ID") ;

GRANT SELECT ON "CNS_PAYMENT" TO "COLLECTOR";

-- DKV_PAYMENT definition

CREATE TABLE "DKV_PAYMENT" 
   (	
	"ID" NUMBER, 
	"CNS_ID" NUMBER, 
	"REQUESTEDON" DATE, 
	"PAIDON" DATE, 
	"AMOUNT" NUMBER, 
	"DKV_ID" VARCHAR2(50), 
	"DOWNLOAD_LINK" VARCHAR2(500), 
	 CONSTRAINT "DKV_PAYMENT_PK" PRIMARY KEY ("ID")
   ) ;

CREATE OR REPLACE TRIGGER "BI_DKV_PAYMENT" 
  before insert on "DKV_PAYMENT"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "DKV_PAYMENT_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER "BI_DKV_PAYMENT" ENABLE;

CREATE UNIQUE INDEX "DKV_PAYMENT_PK" ON "DKV_PAYMENT" ("ID") ;

GRANT SELECT ON "DKV_PAYMENT" TO "COLLECTOR";


-- DKV_PAYMENT foreign keys

ALTER TABLE "DKV_PAYMENT" ADD CONSTRAINT "DKV_CNS_PAYMENT_FK" FOREIGN KEY ("CNS_ID")
	  REFERENCES "CNS_PAYMENT" ("ID") ENABLE;


-- CNS_DOCTORS definition

CREATE TABLE "CNS_DOCTORS" 
   (	
	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50), 
	"SPECIALTY" VARCHAR2(50), 
	 CONSTRAINT "CNS_DOCTORS_PK" PRIMARY KEY ("ID")
   ) ;

CREATE UNIQUE INDEX "CNS_DOCTORS_PK" ON "CNS_PAYMENT" ("ID") ;
/

ALTER TRIGGER "BI_CNS_DOCTORS" ENABLE;

GRANT SELECT ON "CNS_DOCTORS" TO "COLLECTOR";

-- CNS_FACTURE foreign keys

ALTER TABLE "CNS_DOCTORS" ADD CONSTRAINT "CNS_DOCTORS_CNS_FACTURE_FK" FOREIGN KEY ("CNS_DOCTORS")
	  REFERENCES "DOCTORID" ("ID") ENABLE;