CREATE OR REPLACE FORCE VIEW "CARS"."FUEL_PRICES_BY_YEAR" ("YEAR", "AVG FUEL PRICE", "MEDIAN FUEL PRICE", "STDDEV FUEL PRICE") AS 
    SELECT 
	    YEAR_COL,
		ROUND(AVG(price),2) AS "AVG FUEL PRICE",
		ROUND(MEDIAN(price),2) AS "MEDIAN FUEL PRICE",
		ROUND(STDDEV(price),2) AS "STDDEV FUEL PRICE"    
	FROM CARS.FUEL
	JOIN CARS.CALENDAR ON CARS.CALENDAR.DATE_COL = CARS.FUEL.DATE_COL
	group by    CALENDAR.YEAR_COL
	ORDER BY    CALENDAR.YEAR_COL DESC;
