CREATE OR REPLACE FORCE VIEW "CARS"."FUEL_MILEAGE" ("ID_FUEL", "MLG_OLD", "MLG_NEW") AS 
	SELECT 
	    ID_CAR,
	    DATE_FUEL,
	    LAG (KM,1) OVER (PARTITION BY ID_CAR ORDER BY DATE_FUEL DESC) AS next_refuel,
	    LAG (KM,1) OVER (PARTITION BY ID_CAR ORDER BY DATE_FUEL DESC) - DATE_FUEL AS diff
	FROM FUEL
	ORDER BY DATE_FUEL DESC;
	          --  AND ID_FUEL >1900;