CREATE OR REPLACE FORCE VIEW "CARS"."MAINTENANCE_CAR_REPORT" ("DKN", "REFERENCE", "AVG INTERVAl") AS 
	SELECT
			DKN,
			REFERENCE,
			ROUND(avg(INTERVAL_COL),0) as "AVG INTERVAl"
		FROM MAINTENANCE
		JOIN CARS ON CARS.ID_CAR = MAINTENANCE.ID_CAR
		group by DKN, REFERENCE
		ORDER BY DKN DESC, REFERENCE;
