CREATE OR REPLACE FORCE VIEW  "MAINTENANCE_TIMESERIES_STAT" 
	("ID_MAINTENANCE", "ID_CAR", "DKN", "REFERENCE", "DATE_COL", "PREV_DATE", "INTERVAL_DAYS", "INTERVAL_KM") AS 
  SELECT
		ID_MAINTENANCE,
		m.ID_CAR,
		DKN,
		REFERENCE,
		DATE_COL,
		LEAD(DATE_COL,1) OVER (PARTITION BY m.ID_CAR, REFERENCE ORDER BY DATE_COL DESC) PREV_DATE,
		DATE_COL - LEAD(DATE_COL,1) OVER (PARTITION BY m.ID_CAR, REFERENCE ORDER BY DATE_COL DESC) AS "INTERVAL_DAYS",
		INTERVAL_COL AS "INTERVAL_KM"
		FROM CARS.MAINTENANCE m
		JOIN CARS.CARS c ON c.ID_CAR = m.ID_CAR
/