CREATE OR REPLACE FORCE VIEW "CARS"."NEXT_REFUEL" ("ID_CAR", "DKN", "PREVIOUS_DATE", "PREDICTED_DATE", "EXPECTED_PERIOD", "KLM", "KM", "PREDICTED_KM") AS 
	SELECT 
     WHERE DATE_COL > SYSDATE-120
     AND PERIOD != 0
     GROUP BY ID_CAR) prdm
    ON prdm.ID_CAR = mx.ID_CAR            
   JOIN CARS ON mx.ID_CAR = CARS.ID_CAR        
  WHERE mx.MAX_KM = kms.KM        
 AND mx.ID_CAR = kms.ID_CAR        
AND CARS.ACTIVE=1;
