UPDATE FINANCE.CC_CREDIT_CARD
SET 
	ID_CONTRAGENT = (SELECT ID_CONTRAGENT FROM FINANCE.CC_CONTRAGENTS WHERE FINANCE.CC_CONTRAGENTS.LEGAL_NAME = "contragent")
WHERE ID_CONTRAGENT IS NULL;

UPDATE FINANCE.CC_CREDIT_CARD
SET 
	ID_TYPE = (SELECT ID_TYPE FROM FINANCE.CC_CLASSIFIER WHERE FINANCE.CC_CLASSIFIER.ID_CONTRAGENT = FINANCE.CC_CREDIT_CARD.ID_CONTRAGENT)
WHERE ID_TYPE IS NULL;

UPDATE FINANCE.CC_CREDIT_CARD
SET 
	ID_CLASSIFICATION = (SELECT ID_CLASSIFICATION FROM FINANCE.CC_CLASSIFIER WHERE FINANCE.CC_CLASSIFIER.ID_CONTRAGENT = FINANCE.CC_CREDIT_CARD.ID_CONTRAGENT)
WHERE ID_CLASSIFICATION IS NULL;

--UPDATE FINANCE.CC_CREDIT_CARD
--SET 
--	ID_CONTRAGENT = (SELECT ID_CONTRAGENT FROM FINANCE.CC_CONTRAGENTS WHERE FINANCE.CC_CONTRAGENTS.LEGAL_NAME = "contragent")
--WHERE ID_CONTRAGENT IS NULL;

--UPDATE FINANCE.CC_CREDIT_CARD
--SET 
--	ID_TYPE = (SELECT ID_TYPE FROM FINANCE.CC_CONTRAGENTS WHERE FINANCE.CC_CONTRAGENTS.LEGAL_NAME = "contragent")
--WHERE ID_TYPE IS NULL;

--UPDATE FINANCE.CC_CREDIT_CARD
--SET 
--	ID_CLASSIFICATION = (SELECT ID_CLASSIFICATION FROM FINANCE.CC_CONTRAGENTS WHERE FINANCE.CC_CONTRAGENTS.LEGAL_NAME = "contragent")
--WHERE ID_CLASSIFICATION IS NULL;