CREATE OR REPLACE FORCE VIEW "CARS"."FUEL_REFUEL" ("ID_FUEL", "CAR", "DATE", "KM", "AMOUNT", "PRICE", "TOTAL", "FUEL BRAND", "DRIVE TYPE", "MILEAGE", "LKM", "PERIOD", "YEAR", "QUARTER", "MONTH", "DAY", "WEEKDAY") AS 
	SELECT
		CARS.FUEL."ID_FUEL",
		CARS.MAKE || ' ' || CARS.MODEL AS "CAR",
		TO_CHAR(FUEL.DATE_COL, 'YYYY/MM/DD'),
		KM,
		AMOUNT,
		PRICE,
		TOTAL,
		FUEL_NAME AS "FUEL BRAND",
		DRIVE_TYPE,
		MILEAGE,
		LKM,
		PERIOD,
		CALENDAR.YEAR_COL,
		CALENDAR.QUARTER,
		CALENDAR.MONTH_COL,
		CALENDAR.DAY,
		WEEKDAYS.WEEKDAY_BG
	FROM CARS.FUEL
	JOIN CARS.CARS ON CARS.FUEL.ID_CAR=CARS.CARS.ID_CAR
	JOIN CARS.SUPPLIER_FUELS ON CARS.FUEL.ID_BRAND = CARS.SUPPLIER_FUELS.ID_BRAND
	JOIN CARS.DRIVE_TYPE ON CARS.FUEL.ID_DRIVE_TYPE = CARS.DRIVE_TYPE.ID_DRIVE_TYPE
	JOIN CARS.CALENDAR ON CARS.CALENDAR.DATE_COL = CARS.FUEL.DATE_COL
	JOIN CARS.WEEKDAYS ON CARS.WEEKDAYS.ID_WEEKDAY = CARS.CALENDAR.WEEKDAY      
	ORDER BY FUEL.DATE_COL DESC;
