CREATE OR REPLACE FORCE VIEW "CARS"."FUEL_MILEAGE" ("ID_FUEL", "MLG_OLD", "MLG_NEW") AS 
	SELECT 
	    ID_FUEL,
	    LAG (KM,1) OVER (PARTITION BY ID_CAR ORDER BY DATE_COL DESC) AS next_refuel,
	    LAG (KM,1) OVER (PARTITION BY ID_CAR ORDER BY DATE_COL DESC) - KM AS diff
	FROM CARS.FUEL
	ORDER BY DATE_COL DESC;
	          --  AND ID_FUEL >1900;