CREATE OR REPLACE FORCE VIEW "CARS"."FUEL_PRICES_BY_MONTH" ("MONTH", "MAX FUEL PRICE", "MIN FUEL PRICE", "AVG FUEL PRICE", "MEDIAN FUEL PRICE", "STDDEV FUEL PRICE") AS 
  SELECT 
		CALENDAR.MONTH_COL AS "MONTH",
		ROUND(MAX(price),2), ROUND(MIN(price),2),
		ROUND(AVG(price),2) AS "AVG FUEL PRICE",
		ROUND(MEDIAN(price),2) AS "MEDIAN FUEL PRICE",
		ROUND(STDDEV(price),2) AS "STDDEV FUEL PRICE"
	FROM CARS.FUEL
	JOIN CARS.CALENDAR ON CARS.CALENDAR.DATE_COL = CARS.FUEL.DATE_COL
	GROUP BY CALENDAR.MONTH_COL
	ORDER BY CALENDAR.MONTH_COL;
