CREATE OR REPLACE FORCE VIEW "CARS"."MAINTENANCE_SORT" ("ID_MAINTENANCE", "CAR", "DATE", "MILEAGE", "REFERENCE", "TOTAL", "INTERVAL_COL", "CLASSIFICATION", "YEAR", "MONTH", "PRICE_PER_KM") AS 
	SELECT "ID_MAINTENANCE",
		CONCAT( MAKE, CONCAT(' ', MODEL)) AS "CAR",
		CARS.MAINTENANCE."DATE_COL",
		"MILEAGE",
		"REFERENCE",
		"TOTAL",
		"INTERVAL_COL",
		"CLASSIFICATION",
		"YEAR_COL",
		"MONTH_COL",
		"PRICE_PER_KM"
	FROM
		CARS.MAINTENANCE
	JOIN CARS.CLASSIFICATION ON CARS.CLASSIFICATION.ID_CLASSIFICATION = CARS.MAINTENANCE.ID_CLASSIFICATION
	JOIN CARS.CARS ON CARS.CARS.ID_CAR = CARS.MAINTENANCE.ID_CAR    
	JOIN CARS.CALENDAR ON CARS.CALENDAR.DATE_COL = CARS.MAINTENANCE.DATE_COL
	ORDER BY CARS.MAINTENANCE.DATE_COL DESC;
