CREATE TABLE "CARS"."MAINTENANCE" 
   (	"ID_MAINTENANCE" NUMBER NOT NULL ENABLE, 
	"ID_CAR" NUMBER, 
	"DATE_COL" DATE, 
	"MILEAGE" NUMBER, 
	"REFERENCE" VARCHAR2(255), 
	"TOTAL" NUMBER, 
	"INTERVAL_COL" NUMBER, 
	"ID_CLASSIFICATION" NUMBER, 
	"PRICE_PER_KM" NUMBER, 
	 CONSTRAINT "MAINTENANCE_PK" PRIMARY KEY ("ID_MAINTENANCE", "ID_CAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5814722197993291"  ENABLE, 
	 CONSTRAINT "MAINTENANCE_CLASSIFICATION_FK" FOREIGN KEY ("ID_CLASSIFICATION")
	  REFERENCES "CARS"."CLASSIFICATION" ("ID_CLASSIFICATION") ENABLE, 
	 CONSTRAINT "MAINTENANCE_CARS_FK" FOREIGN KEY ("ID_CAR")
	  REFERENCES "CARS"."CARS" ("ID_CAR") ENABLE, 
	 CONSTRAINT "MAINTENANCE_FK_CALENDAR" FOREIGN KEY ("DATE_COL")
	  REFERENCES "CARS"."CALENDAR" ("DATE_COL") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5814722197993291";
