CREATE TABLE "FINANCE"."CC_CREDIT_CARD" 
   (	"reference" VARCHAR2(255) NOT NULL ENABLE, 
	"date_time" DATE, 
	"value_date" DATE, 
	"debit" NUMBER(38,2), 
	"credit" NUMBER(38,2), 
	"trname" VARCHAR2(500), 
	"contragent" VARCHAR2(500), 
	"rem_i" VARCHAR2(500), 
	"rem_ii" VARCHAR2(500), 
	"rem_iii" VARCHAR2(500), 
	"YEAR_CC" NUMBER, 
	"MONTH_CC" NUMBER, 
	"DAY_CC" NUMBER, 
	"ID_WEEKDAY" NUMBER, 
	"PERIOD" NUMBER, 
	"ID_CONTRAGENT" NUMBER, 
	"ID_TYPE" NUMBER, 
	"ID_CLASSIFICATION" NUMBER, 
	 CONSTRAINT "CC_CREDIT_CARD_CON" PRIMARY KEY ("reference")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "CC_CREDIT_CARD_WEEKDAYS_FK" FOREIGN KEY ("ID_WEEKDAY")
	  REFERENCES "FINANCE"."WEEKDAYS" ("ID_WEEKDAY") ENABLE, 
	 CONSTRAINT "CC_CREDIT_CARD_CC_CONTRAG_FK" FOREIGN KEY ("ID_CONTRAGENT")
	  REFERENCES "FINANCE"."CC_CONTRAGENTS" ("CONTRAGENT_ID") DISABLE, 
	 CONSTRAINT "CC_CREDIT_CARD_CC_TYPE_FK" FOREIGN KEY ("ID_TYPE")
	  REFERENCES "FINANCE"."CC_TYPE" ("ID_TYPE") ENABLE, 
	 CONSTRAINT "CC_CREDIT_CARD_CC_CLASS_FK" FOREIGN KEY ("ID_CLASSIFICATION")
	  REFERENCES "FINANCE"."CC_CLASSIFICATION" ("ID_CLASSIFICATION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4788810271599456"  ENABLE ROW MOVEMENT;
