DROP TABLE  "WEEKDAYS" CASCADE CONSTRAINTS;
DROP TABLE  "CALENDAR" CASCADE CONSTRAINTS;
DROP TABLE  "CARS" CASCADE CONSTRAINTS;
DROP TABLE  "CLASSIFICATION" CASCADE CONSTRAINTS;
DROP TABLE  "DRIVE_TYPE" CASCADE CONSTRAINTS;
DROP TABLE  "SUPPLIER_FUELS" CASCADE CONSTRAINTS;
DROP TABLE  "FUEL"  CASCADE CONSTRAINTS;
DROP TABLE  "FUELTMP"  CASCADE CONSTRAINTS;
DROP TABLE  "FUEL_APP"  CASCADE CONSTRAINTS;
DROP TABLE  "MAINTENANCE"  CASCADE CONSTRAINTS;
DROP TABLE  "MAINTENANCE_PRP"  CASCADE CONSTRAINTS;
DROP TABLE  "OWNER"  CASCADE CONSTRAINTS;

DROP FUNCTION  "MILEAGEFUNC"  CASCADE CONSTRAINTS; 
DROP FUNCTION "CUSTOM_HASH"  CASCADE CONSTRAINTS;
DROP FUNCTION "CUSTOM_AUTH"  CASCADE CONSTRAINTS;

DROP INDEX  "CARS_DKN_IDX";
DROP INDEX  "FUEL_DATE_DESC_IDX";
DROP INDEX  "WEEKDAYS_IDX1";

DROP PROCEDURE  "SUPPLIER_REPORT"  CASCADE CONSTRAINTS;

 DROP SEQUENCE "OWNER_SEQ";
 DROP SEQUENCE "MAINTENANCE_PRP_SEQ";
 DROP SEQUENCE "MAINTENANCE_PREP_SEQ";
 DROP SEQUENCE "FUELTMP_SEQ";
 DROP SEQUENCE "CARS_SEQ";
 DROP SEQUENCE "ARTICULES_SEQ";

DROP TRIGGER  "bi_MAINTENANCE_PRP";
DROP TRIGGER  "bi_FUELTMP";
DROP TRIGGER  "FUEL_CALENDAR";
DROP TRIGGER  "FUEL_APP_T1";
DROP TRIGGER  "FUEL_APP_CALENDAR";
DROP TRIGGER  "CALENDAR_T1";
DROP TRIGGER  "BI_OWNER";
DROP TRIGGER  "BI_FUEL_APP";
DROP TRIGGER  "BI_CLASSIFICATION";
DROP TRIGGER  "BI_CARS";

DROP VIEW  "FUEL_CONSUMPTION_PREDICTION" CASCADE CONSTRAINTS;
DROP VIEW  "FUEL_CONSUMPTION_REPORT" CASCADE CONSTRAINTS;
DROP VIEW  "FUEL_MILEAGE" CASCADE CONSTRAINTS;
DROP VIEW  "FUEL_PRICES_BY_MONTH" CASCADE CONSTRAINTS;
DROP VIEW  "FUEL_PRICES_BY_QUARTER" CASCADE CONSTRAINTS;
DROP VIEW  "FUEL_PRICES_BY_YEAR" CASCADE CONSTRAINTS;
DROP VIEW  "FUEL_REFUEL" CASCADE CONSTRAINTS;
DROP VIEW  "FUEL_SORTED" CASCADE CONSTRAINTS;
DROP VIEW  "MAINTENANCE_CAR_REPORT" CASCADE CONSTRAINTS;
DROP VIEW  "MAINTENANCE_PPK" CASCADE CONSTRAINTS;
DROP VIEW  "MAINTENANCE_PREDICTION" CASCADE CONSTRAINTS;
DROP VIEW  "MAINTENANCE_SORT" CASCADE CONSTRAINTS;
DROP VIEW  "MAINTENANCE_STAT" CASCADE CONSTRAINTS;
DROP VIEW  "MAINTENANCE_TIMESERIES_STAT" CASCADE CONSTRAINTS;
DROP VIEW  "MILEAGE_STAT" CASCADE CONSTRAINTS;
DROP VIEW  "NEXT_REFUEL" CASCADE CONSTRAINTS;
DROP VIEW  "TCO" CASCADE CONSTRAINTS;
DROP VIEW  "V_FUEL_CONS_PER_DRVTYPE" CASCADE CONSTRAINTS;
DROP VIEW  "V_SUPPLIER_REPORT" CASCADE CONSTRAINTS;