DROP TABLE  "WEEKDAYS" CASCADE CONSTRAINTS;
/
DROP TABLE  "CALENDAR" CASCADE CONSTRAINTS;
/
DROP TABLE  "CARS" CASCADE CONSTRAINTS;
/
DROP TABLE  "CLASSIFICATION" CASCADE CONSTRAINTS;
/
DROP TABLE  "DRIVE_TYPE" CASCADE CONSTRAINTS;
/
DROP TABLE  "SUPPLIER_FUELS" CASCADE CONSTRAINTS;
/
DROP TABLE  "FUEL"  CASCADE CONSTRAINTS;
/
DROP TABLE  "FUELTMP"  CASCADE CONSTRAINTS;
/
DROP TABLE  "FUEL_APP"  CASCADE CONSTRAINTS;
/
DROP TABLE  "MAINTENANCE"  CASCADE CONSTRAINTS;
/
DROP TABLE  "MAINTENANCE_PRP"  CASCADE CONSTRAINTS;
/
DROP TABLE  "OWNER"  CASCADE CONSTRAINTS;
/

DROP FUNCTION  "MILEAGEFUNC"  CASCADE CONSTRAINTS; 
/

CREATE OR REPLACE FUNCTION  "CUSTOM_HASH"  CASCADE CONSTRAINTS;
/

CREATE OR REPLACE FUNCTION  "CUSTOM_AUTH"  CASCADE CONSTRAINTS;
/

CREATE INDEX  "CARS_DKN_IDX" ON  "CARS" ("DKN", "ACTIVE", "VALID_FROM", "VALID_TILL")
/
CREATE INDEX  "FUEL_DATE_DESC_IDX" ON  "FUEL" ("ID_CAR", "DATE_COL" DESC, "KM", "AMOUNT", "PRICE", "TOTAL", "ID_BRAND", "ID_DRIVE_TYPE", "MILEAGE", "LKM", "PERIOD")
/
CREATE UNIQUE INDEX  "WEEKDAYS_IDX1" ON  "WEEKDAYS" ("ID_WEEKDAY", "WEEKDAY_NAME", "WEEKDAY_BG")
/
CREATE OR REPLACE PROCEDURE  "SUPPLIER_REPORT"  CASCADE CONSTRAINTS;
/

 DROP SEQUENCE   "OWNER_SEQ"  CASCADE CONSTRAINTS;
/
 DROP SEQUENCE   "MAINTENANCE_PRP_SEQ"  CASCADE CONSTRAINTS;
/
 DROP SEQUENCE   "MAINTENANCE_PREP_SEQ"  CASCADE CONSTRAINTS;
/
 DROP SEQUENCE   "FUELTMP_SEQ"  CASCADE CONSTRAINTS;
/
 DROP SEQUENCE   "CARS_SEQ"  CASCADE CONSTRAINTS;
/
DROP TRIGGER  "bi_MAINTENANCE_PRP" CASCADE CONSTRAINTS;
/
DROP TRIGGER  "bi_FUELTMP" CASCADE CONSTRAINTS;
/
DROP TRIGGER  "FUEL_CALENDAR" CASCADE CONSTRAINTS;
/
DROP TRIGGER  "FUEL_APP_T1" CASCADE CONSTRAINTS;
/
DROP TRIGGER  "FUEL_APP_CALENDAR" CASCADE CONSTRAINTS;
/
DROP TRIGGER  "CALENDAR_T1"CASCADE CONSTRAINTS;
/
DROP TRIGGER  "BI_OWNER"CASCADE CONSTRAINTS;
/
DROP TRIGGER  "BI_FUEL_APP" CASCADE CONSTRAINTS;
/
DROP TRIGGER  "BI_CLASSIFICATION" CASCADE CONSTRAINTS;
/
DROP TRIGGER  "BI_CARS" CASCADE CONSTRAINTS;
/
DROP VIEW  "FUEL_CONSUMPTION_PREDICTION" CASCADE CONSTRAINTS;
/
DROP VIEW  "FUEL_CONSUMPTION_REPORT" CASCADE CONSTRAINTS;
/
DROP VIEW  "FUEL_MILEAGE" CASCADE CONSTRAINTS;
/
DROP VIEW  "FUEL_PRICES_BY_MONTH" CASCADE CONSTRAINTS;
/
DROP VIEW  "FUEL_PRICES_BY_QUARTER" CASCADE CONSTRAINTS;
/
DROP VIEW  "FUEL_PRICES_BY_YEAR" CASCADE CONSTRAINTS;
/
DROP VIEW  "FUEL_REFUEL" CASCADE CONSTRAINTS;
/
DROP VIEW  "FUEL_SORTED" CASCADE CONSTRAINTS;
/
DROP VIEW  "MAINTENANCE_CAR_REPORT" CASCADE CONSTRAINTS;
/
DROP VIEW  "MAINTENANCE_PPK" CASCADE CONSTRAINTS;
/
DROP VIEW  "MAINTENANCE_PREDICTION" CASCADE CONSTRAINTS;
/
DROP VIEW  "MAINTENANCE_SORT" CASCADE CONSTRAINTS;
/
DROP VIEW  "MAINTENANCE_STAT" CASCADE CONSTRAINTS;
/
DROP VIEW  "MAINTENANCE_TIMESERIES_STAT" CASCADE CONSTRAINTS;
/
DROP VIEW  "MILEAGE_STAT" CASCADE CONSTRAINTS;
/
DROP VIEW  "NEXT_REFUEL" CASCADE CONSTRAINTS;
/
DROP VIEW  "TCO" CASCADE CONSTRAINTS;
/
DROP VIEW  "V_FUEL_CONS_PER_DRVTYPE" CASCADE CONSTRAINTS;
/
DROP VIEW  "V_SUPPLIER_REPORT" CASCADE CONSTRAINTS;
/
