CREATE TABLE  "DC_FIB_SMART" 
   (	
	"ID" NUMBER, 
	"REFERENCE" VARCHAR2(30), 
	"DATETIME" DATE, 
	"VALUEDATE" DATE, 
	"DEBIT" NUMBER, 
	"CREDIT" NUMBER, 
	"TRNAME" VARCHAR2(255), 
	"CONTRAGENT" VARCHAR2(255), 
	"REM_I" VARCHAR2(255), 
	"REM_II" VARCHAR2(255), 
	"REM_III" VARCHAR2(255), 
	 CONSTRAINT "DC_FIB_SMART_PK" PRIMARY KEY ("ID") ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "bi_DC_FIB_SMART" 
  before insert on "DC_FIB_SMART"              
  for each row 
begin  
  if :new."ID" is null then
    select "DC_FIB_SMART_SEQ".nextval into :new."ID" from sys.dual;
  end if;
end;

/
ALTER TRIGGER  "bi_DC_FIB_SMART" ENABLE
/

CREATE OR REPLACE FORCE VIEW  "V_DC_FIB_BALANCE" ("ID", "REFERENCE", "DATETIME", "VALUEDATE", "DEBIT", "CREDIT", "TRNAME", "CONTRAGENT", "REM_I", "REM_II", "REM_III", "SUM_DEBIT", "SUM_CREDIT", "RUNNING_BALANCE") AS 
  SELECT 
	ID
	,REFERENCE
	,DATETIME
	,VALUEDATE
	,DEBIT
	,CREDIT
	,TRNAME 
	,CONTRAGENT
	,REM_I 
	,REM_II 
	,REM_III 
	,(SELECT SUM(DEBIT) FROM DC_FIB_SMART dfs2 WHERE dfs2.DATETIME <= dfs.DATETIME) AS SUM_DEBIT
	,(SELECT SUM(CREDIT) FROM DC_FIB_SMART dfs2 WHERE dfs2.DATETIME <= dfs.DATETIME) AS SUM_CREDIT
	,(SELECT SUM(CREDIT) FROM DC_FIB_SMART dfs2 WHERE dfs2.DATETIME <= dfs.DATETIME) - (SELECT SUM(DEBIT) FROM DC_FIB_SMART dfs2 WHERE dfs2.DATETIME <= dfs.DATETIME) AS RUNNING_BALANCE
	FROM DC_FIB_SMART dfs 
ORDER BY DATETIME
/

CREATE OR REPLACE FORCE VIEW  "V_DC_FIB_CONTRAGENTS_BY_YEAR" ("YEAR", "CONTRAGENT", "DEBIT", "CREDIT") AS 
  SELECT 
		EXTRACT(year FROM dfs2.DATETIME) "YEAR"
		,CONTRAGENT
		,SUM(DEBIT) AS DEBIT
		,SUM(CREDIT) AS CREDIT
	FROM DC_FIB_SMART dfs2 
	GROUP BY EXTRACT(year FROM dfs2.DATETIME) ,CONTRAGENT 
	ORDER BY EXTRACT(year FROM dfs2.DATETIME) DESC, dfs2.CONTRAGENT
/