DROP TABLE "PRE_RP" CASCADE CONSTRAINTS;
DROP TABLE "RP_ACCOUNTS" CASCADE CONSTRAINTS;
DROP TABLE "RP_SERVICE" CASCADE CONSTRAINTS;
DROP TABLE "RP_CONTRAGENT" CASCADE CONSTRAINTS;
DROP TABLE  "RP_RECURRING_PAYMENTS" CASCADE CONSTRAINTS;

DROP SEQUENCE "RP_SERVICE_SEQ" CASCADE CONSTRAINTS;
DROP SEQUENCE "RP_RECURRING_PAYMENTS_SEQ" CASCADE CONSTRAINTS;
DROP SEQUENCE "REC_ACCOUNT_SEQ" CASCADE CONSTRAINTS;
DROP SEQUENCE "PRE_RP_SEQ" CASCADE CONSTRAINTS;
DROP SEQUENCE "PRE_RECURRING_PAYMENTS_SEQ" CASCADE CONSTRAINTS;

DROP VIEW "PRE_RP_SORTED" CASCADE CONSTRAINTS;
DROP VIEW "PR_STAT_QUARTER" CASCADE CONSTRAINTS;
DROP VIEW "RP_DESCRIPTIONS" CASCADE CONSTRAINTS;
DROP VIEW "RP_SORTED"  CASCADE CONSTRAINTS;
DROP VIEW "RP_STAT" CASCADE CONSTRAINTS;
DROP VIEW "RP_YEAR_STAT" CASCADE CONSTRAINTS;

DROP procedure "ETL_RECURRING_PAYMENT";